### ISSUE TITLE
Consistency check? physical = source + comment + empty?

### ISSUE THREAD

**Issue by manatarms** [flosse/sloc#90]
I wanted to make sure I wasn't losing my mind. 
I wanted to confirm if the total physical lines of code should = source + comment + empty?
I am getting results where it does not. Does that mean something is wrong, or am I assuming something here?
Thanks!

**Comment by zwrawr** [comment]
Based on my repo, it looks like mixed lines get counted as comments and source code (which makes sense). But even when i account for that it doesn't match up exactly.  
`physical ~= source + comment - mixed + empty` is two lines off for my repo.

**Comment by flosse** [comment]
Would you mind to write a testcase?

**Comment by flosse** [comment]
FYI: #99

**Comment by zwrawr** [comment]
Figured it out from looking at source. 

The equation in the source is  `  source  = total - comment - empty + blockEmpty + mixed`
Which is source = physical - comment - empty + empty_lines_in_block_comments + mixed`

Empty lines in block comments contribute to the number of block comment lines and the number of empty lines (similar to how mixed works) so we need to add the number back on to stop them being counted twice.

The output looked wrong because the formatter doesn't output the number of empty lines in block comments, but sloc was working fine.
